services:
  windrose:
    image: rhavinx/windrose:latest
    container_name: windrose
    stop_grace_period: 30s
    environment:
      TZ: "UTC"
      # PUID: "1000"
      # PGID: "1000"
      SKIP_UPDATE: "0"
      SERVER_NAME: "My Windrose Server"
      INVITE_CODE: "changeme"
      SERVER_PASSWORD: "changeme"
      MAX_PLAYERS: "4"
      GAME_PORT: "7777"
      # USE_DIRECT_CONNECTION: "true"
      # DIRECT_CONNECTION_ADDRESS: "your.public.ip"
      # REGION: ""
      # P2P_PROXY_ADDRESS: "127.0.0.1"
      # REMOVE_SERVER_FILES: "0"
    volumes:
      - /path/to/server:/home/steam/windrose/server
      - /path/to/data:/home/steam/windrose/data
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
    restart: unless-stopped
